[package]
name = "sbepis"
version = "0.1.0"
edition = "2021"

[lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

[features]
debug = ["inspector", "terminal", "rapier_debug"]
default = []
inspector = ["dep:bevy-inspector-egui", "bevy_panorbit_camera/bevy_egui"]
spawn_debug_notes_on_staff = []
terminal = []
rapier_debug = []

[dependencies]
bevy = { version = "0.14.1", features = ["wav", "mp3", "wayland"] }
bevy-inspector-egui = { version = "0.25.1", optional = true }
bevy_panorbit_camera = "0.19.1"
bevy_rapier3d = { version = "0.27.0", features = ["serde-serialize"] }
image = "0.25.2"
itertools = "0.13.0"
leafwing-input-manager = "0.15.0"
num-traits = "0.2.19"
winit = "0.30.4"
rand = "0.8.5"
interpolation = "0.3.0"
bevy_renet = { version = "0.0.12", features = ["serde"] }
bincode = "1.3.3"
serde = { version = "1.0.210", features = ["derive"] }

[build-dependencies]
winres = "0.1"
